Do not create parent directories for new objects
GoogleCloudDataproc/hadoop-connectors pull request #468
Opened 2020-10-12 17:49 UTC by medb

Explicit parent directories objects are not necessary because they will be inferred automatically if object exists.

Fixes #356

2020-10-12 17:49 UTC, medb commented
/gcbrun

2020-10-13 04:09 UTC, hongyegong requested changes
I think this change deserves a release notes?

2020-10-14 21:09 UTC, medb commented
> I think this change deserves a release notes?

Done.

2020-10-14 21:11 UTC, hongyegong approved these changes

2020-10-14 21:34 UTC, merged