Added javax.annotation-api.version dep for grpc 1.32.1
GoogleCloudDataproc/hadoop-connectors pull request #480
Opened 2020-10-27 22:30 UTC by hongyegong

Current maven build command fails because of this updated dependency in gRPC.

2020-10-27 22:33 UTC, medb requested changes
What exactly fails if presubmit succeeds?

2020-10-27 22:41 UTC, hongyegong commented
> What exactly fails if presubmit succeeds?

I am looking into this but it consistently fails for me locally when I run unit tests `mvn -Phadoop2 clean test`, error message is

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project gcsio: Compilation failure
[ERROR] <home_path>/Documents/workspace/bigdata-interop/gcsio/target/generated-sources/protobuf/grpc-java/com/google/google/storage/v1/StorageGrpc.java:[23,18] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR] 
```

2020-10-28 01:30 UTC, hongyegong commented
> > What exactly fails if presubmit succeeds?
> 
> I am looking into this but it consistently fails for me locally when I run unit tests `mvn -Phadoop2 clean test`, error message is
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project gcsio: Compilation failure
> [ERROR] <home_path>/Documents/workspace/bigdata-interop/gcsio/target/generated-sources/protobuf/grpc-java/com/google/google/storage/v1/StorageGrpc.java:[23,18] cannot find symbol
> [ERROR]   symbol:   class Generated
> [ERROR]   location: package javax.annotation
> [ERROR] 
> ```

Ok I was not able to figure out why it doesn't reproducible on presubmit by running old cloud build jobs. But it seems real as I run mvn command with head code on master branch and can be reproducible on both laptop and my workstation.

2020-10-28 01:47 UTC, medb commented
> Ok I was not able to figure out why it doesn't reproducible on presubmit by running old cloud build jobs. But it seems real as I run mvn command with head code on master branch and can be reproducible on both laptop and my workstation.

Maybe theres is issue with Maven version, because build works for me at `HEAD`:

```
$ git log --oneline --max-count=1
c3d30ef2 (HEAD) Update CONFIGURATION.md

$ ./mvnw -Phadoop2 clean test

. . .

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:46 min
[INFO] Finished at: 2020-10-27T18:40:05-07:00
[INFO] ------------------------------------------------------------------------
```

2020-10-28 17:51 UTC, medb requested changes
Also, make sure that you use Java 8 in Maven build.

2020-10-28 19:07 UTC, hongyegong commented
Turns out to be java version problem. Updated gRPC version auto-generated code that breaks Java11 unless extra dependency added.
Need to point maven to Java8 by setting JAVA_HOME to Java8 home dir.

Close this for now.

2020-10-28 19:07 UTC, closed without merging