List +1 object only when listed prefix not included in the result
GoogleCloudDataproc/hadoop-connectors pull request #497
Opened 2020-11-23 22:37 UTC by medb

2020-11-23 22:38 UTC, medb commented
/gcbrun

2020-11-24 05:53 UTC, functicons requested changes

2020-11-24 05:53 UTC, functicons commented on gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java
> +    // List +1 object if prefix should not be included in the result,
Add an example to better explain why.

2020-11-24 17:58 UTC, medb commented on gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java
> +    // List +1 object if prefix should not be included in the result,
Done.

2020-11-24 18:50 UTC, functicons approved these changes

2020-11-24 20:26 UTC, merged