Invalidate current request to gcs if read request beyond range offset in gRPC channel
GoogleCloudDataproc/hadoop-connectors pull request #576
Opened 2021-06-18 09:45 UTC by mprashanthsagar

2021-06-18 09:45 UTC, mprashanthsagar commented
/gcbrun

2021-06-18 14:46 UTC, davidrabinowitz requested changes

2021-06-18 14:46 UTC, davidrabinowitz commented on gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageGrpcReadChannel.java
> +    if ((effectivePosition + byteBuffer.remaining()) > (contentChannelEndOffset)) {
can be simplified: `return (effectivePosition + byteBuffer.remaining()) > (contentChannelEndOffset);`

2021-06-18 14:46 UTC, davidrabinowitz commented on gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageGrpcReadChannel.java
> +      position = position + bytesToSkipBeforeReading;
nit: `position += bytesToSkipBeforeReading` to keep code consistency

2021-06-18 14:46 UTC, davidrabinowitz commented on gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageGrpcReadChannel.java
> +      position = position + bytesToSkipBeforeReading;
nit: `position += bytesToSkipBeforeReading` to keep code consistency

2021-06-18 21:54 UTC, davidrabinowitz approved these changes

2021-06-23 06:43 UTC, mayanks approved these changes
LGTM

2021-06-23 10:27 UTC, merged