Reduced Hadoop version to ensure 2.8 compatibility
GoogleCloudDataproc/hadoop-connectors pull request #628
Opened 2021-09-30 20:27 UTC by davidrabinowitz

2021-09-30 20:27 UTC, davidrabinowitz commented
/gcbrun

2021-09-30 21:49 UTC, medb requested changes

2021-09-30 21:49 UTC, medb commented on pom.xml
> +    <hadoop.two.version>2.8.0</hadoop.two.version>
May we use 2.7.7 instead - it still widely used?

2021-09-30 22:49 UTC, davidrabinowitz commented
/gcbrun

2021-09-30 23:03 UTC, medb requested changes

2021-09-30 23:03 UTC, medb commented on bigquery/pom.xml
> +                  <include>org.apache.avro</include>
Will this include avro in shaded jar? If so, we can not do this.

2021-11-28 11:07 UTC, mprashanthsagar commented
@davidrabinowitz Is this PR still relevant ?

2021-11-29 17:57 UTC, davidrabinowitz commented
Yes, but not urgent. It is to keep us supporting old Hadoop versions.

2021-12-28 16:19 UTC, medb commented
Seems like it will be better to keep status quo than try to fix this, taking into account that this will be a maintenance branch anyway.

2021-12-28 16:19 UTC, closed without merging