Configure error prone analysis and fix build failures
GoogleCloudDataproc/hadoop-connectors pull request #683
Opened 2022-01-18 17:23 UTC by medb

2022-01-18 17:46 UTC, mprashanthsagar approved these changes

2022-01-18 17:49 UTC, mprashanthsagar requested changes
Waiting on build fix. Let's also cherry pick this change to branch 2.2.x

2022-01-19 04:15 UTC, medb commented
> Waiting on build fix. Let's also cherry pick this change to branch 2.2.x

Definitely, but Error Prone seems to not work on Java 8, so only code fixes can be cherry picked.

2022-01-19 04:44 UTC, mprashanthsagar approved these changes

2022-01-19 05:52 UTC, merged